### ISSUE TITLE
翻译的条目有点少啊。

### ISSUE THREAD

**Issue by xuetengfei** [Haojen/alfred-Parrot#1]
嗯。总体很好用的。就是百度的翻译，结果条目很少，有的时候翻译只有一个结果，而且翻译的并不准确。是百度api的数据问题，还是alfred-Parrot的问题呢？？

**Comment by Haojen** [comment]
这个是百度 api 的问题，之前我本来想只用百度的，结果发现百度翻译返回的结果太少了，无奈后又加上了网易的
