### ISSUE TITLE
有道升级为有道智云

### ISSUE THREAD

**Issue by xuetengfei** [Haojen/alfred-Parrot#2]
有道升级为有道智云，不能申请个人的key了。17年12月31日后，之前的key全部失效。能不能加入有道智云的那个api接口，我看了一下，好复杂。

**Comment by Haojen** [comment]
@xuetengfei  写这个功能的时候，有接到过有道的通知。但那时候技术选型已经决定了，所以没有使用。
会在过期之前，用有道智云重写一下
多谢你的反馈和使用

**Comment by Haojen** [comment]
@xuetengfei  已经升级到有道智云， 无需任何配置按照教程安装后就能用
