### ISSUE TITLE
更新了node到8.12 ，就不能用了

### ISSUE THREAD

**Issue by HongTao-Huang** [Haojen/alfred-Parrot#5]
> alfred-parrot@1.1.0 postinstall /usr/local/lib/node_modules/alfred-parrot
> alfy-init

{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/huanght/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-parrot/node_modules/resolve-alfred-prefs/index.js:15:10)
    at <anonymous>

    at Promise.all.then.arr (/usr/local/lib/node_modules/alfred-parrot/node_modules/execa/index.js:201:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Alfred preferences not found at location /Users/huanght/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-parrot/node_modules/resolve-alfred-prefs/index.js:15:10)\n    at <anonymous>\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-parrot@1.1.0 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alfred-parrot@1.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/huanght/.npm/_logs/2018-09-28T02_45_39_173Z-debug.log

**Comment by Haojen** [comment]
@HongTao-Huang  I don't have some issues, can you tell me more about this error details ? (I update 8.9.4)

**Comment by Haojen** [comment]
@HongTao-Huang  @BaiLu233   The problem has been fixed.
